name: Check bundleO

on:
  push:
    paths:
      - 'bundleO/**'
  pull-request:
    paths:
      - 'bundleO/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bundleO
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Checkthat app starts
        run: node -e "require('./index.js')"
